version: '3.8'

networks:
  boilerplate:
    driver: bridge

volumes:
  pgdata:
  mongodata:

services:
  # Exemplo: usando mongo
  mongo:
    networks:
      - boilerplate
    container_name: boilerplate-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./tmp/backups:/data/backups
      - mongodata:/data/db

      # Exemplo: usando postgres
  psql:
    networks:
      - boilerplate
    container_name: boilerplate-psql
    image: postgres:12.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=boilerplate
      - POSTGRES_USER=boilerplate
      - POSTGRES_PASSWORD=boilerplate
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    networks:
      - boilerplate
    build:
      context: .
    image: boilerplate-api
    container_name: boilerplate-api
    command: yarn run start:dev
    build:
      context: .
    volumes:
      - ./:/code
      - ./node_modules:/code/node_modules
    ports:
      - 3000:3000
    links:
      - mongo
      - psql
    depends_on:
      - mongo
      - psql
